export const SEND_TOKEN = "Send Token";
export const SEND_ETH = "Send ETH";
export const BUY_REWARD = "Buy Reward";
export const DEPOSIT = "Deposit";
export const EXCHANGE_SELL_ESCROW = "Exchange Sell Escrow";
export const EXCHANGE_SELL_RELEASE = "Exchange Sell Release";
export const BUY_STORE_ITEM = "Buy Store Item";

export const STORAGE_PIN_CODE = "STORAGE_PIN_CODE";
export const STORAGE_ACCOUNT = "STORAGE_ACCOUNT";
export const STORAGE_SECURE_ACCOUNT = "STORAGE_SECURE_ACCOUNT";
export const STORAGE_SECURE = "STORAGE_SECURE";
export const STORAGE_LATEST_UPDATED_TRANSACTIONS = "STORAGE_LATEST_UPDATED_TRANSACTIONS";
export const STORAGE_LATEST_UPDATED_CONTACTS = "STORAGE_LATEST_UPDATED_CONTACTS";
export const STORAGE_SETTINGS = "STORAGE_SETTINGS";

export const DATABASE_LOADED = "DATABASE_LOADED";
export const CONTACT_LOADED = "CONTACT_LOADED";
export const CONTACT_UPDATED = "CONTACT_UPDATED";
export const CONTACT_REMOVED = "CONTACT_REMOVED";
export const TRANSACTION_LOADED = "TRANSACTION_LOADED";
export const TRANSACTION_UPDATED = "TRANSACTION_UPDATED";
export const TRANSACTION_REMOVED = "TRANSACTION_REMOVED";
export const CLEARED = "CLEARED";
